FROM python:latest

RUN mkdir /app/
WORKDIR /app/

COPY ./src/requirements.txt /app/requirements.txt
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN pip install --upgrade google-api-python-client

COPY ./src/ /app/

ENV FLASK_APP=server.py
CMD flask run -h 0.0.0 -p 5000
